theme: jekyll-theme-minimal
title: Cool Business Homepage
description: Welcome!
text: ================================================================

button: Button
title: Enter Cool Title Here

text: ================================================================
